### ISSUE TITLE
Sample plugin doesn't work out of the box

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-sample#2]
As a user new to Graylog plugin development, I would expect the official sample plugin (referenced in the documentation) to work out of the box.

Unfortunately, the experience with this repository is not very good:

```text
$ git clone git@github.com:Graylog2/graylog-plugin-sample.git
Cloning into 'graylog-plugin-sample'...
remote: Counting objects: 94, done.
remote: Total 94 (delta 0), reused 0 (delta 0), pack-reused 94
Receiving objects: 100% (94/94), 17.83 KiB | 0 bytes/s, done.
Resolving deltas: 100% (21/21), done.
$ cd graylog-plugin-sample/
$ mvn install
[INFO] Scanning for projects...
[WARNING] The project org.graylog.plugins:graylog-plugin-sample:jar:1.0.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building graylog-plugin-sample 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.graylog2:graylog2-plugin:jar:2.0.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.367 s
[INFO] Finished at: 2017-07-17T17:08:00+02:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project graylog-plugin-sample: Could not resolve dependencies for project org.graylog.plugins:graylog-plugin-sample:jar:1.0.0-SNAPSHOT: Could not find artifact org.graylog2:graylog2-plugin:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by brendenblack** [comment]
I ran in to the same issue (and many others) this weekend. Seconding that the experience is 'not very good'  

In your other issue you say that the example & documentation "don't reflect how we build Graylog plugins nowadays"; do you know where to find info on how they are built?

**Comment by billmurrin** [comment]
My Graylog Development journey has definitely been a learning experience, to say the least. I have learned tons of things this year during my journey to make a plugin. 

I genuinely admire the work of the GL team and enjoy being part of this great community, but I honestly feel that the dev experience is really confusing, especially for new users, or those with a completely different programming background that want to jump in and get started. Nearly all the samples fail out of the box - this does not inspire confidence for the new plugin developer.

I believe that making plugin dev easier to understand and supported with solid examples incrementally updated with each GL release - will help drive adoption of the product and support a larger dev ecosystem. 

When the plugin architecture is changing I think it would really cool to see a GL Blog/Dev Forum post concerning the upcoming changes so the Plugin Authors know what is going to change/break plugins in the next release and can make the necessary changes. (E.g. In release X, we are moving to this version of plugin-name and you'll need to change the format to this in order to be compatible with graylog-web-plugin).

**Comment by joschi** [comment]
The 2.3 and 2.4 branches are now building out of the box (if the Graylog2/graylog2-server checkout exists at `../graylog2-server` on the local filesystem) and on Travis CI.

* `2.3`: https://travis-ci.org/Graylog2/graylog-plugin-sample/builds/391777930
* `2.4`: https://travis-ci.org/Graylog2/graylog-plugin-sample/builds/391777765
